name: Sync from upstream
on:
  schedule:
    - cron: '0 19 * * *'   # 每天 UTC 19:00＝北京 03:00
  workflow_dispatch:        # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/6dylan6/jdpro.git
          git fetch upstream

      - name: Rebase onto upstream
        run: |
          git checkout main           # 或 master
          git rebase upstream/main

      - name: Push to fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin main --force-with-lease
